apiVersion: v1
kind: Service
metadata:
  name: telecomai
  labels:
    app: telecomai
spec:
  type: ClusterIP
  selector:
    app: telecomai
  ports:
    - name: http
      port: 80
      targetPort: 8000
